
---

# Análise Exploratória de Dados (EDA) - Carteira Ibovespa

Esse documento consiste em uma análise exploratória dos dados de cotação diária da carteira Ibovespa obtidos pela api Yfinance. A base de dados inclui 19,7 mil registros de dados de um conjunto de 84 ações, contendo colunas de valor e volume negociadas diariamente, dados de categoria, setor e indústria, e colunas criadas no processo de feature engineering.

**Target**

* Predição do **Close_diff_t_plus_1**: Valor de fechamento para o próximo dia (Close_diff t+1).

---

 **Carregamento dos dados**
* Carregamento do datasets `tbl_carteira_ibovespa` com informações setoriais da carteira Ibovespa.
* Carregamento do datasets `tbl_cotacao_ibovespa` com cotações diárias da ações extraídas da Api do Yfinance.

 **Feature Engineering** 
 *(Todas essas transformações serão integradas a um processo de ETL no AWS Glue.)*

* Junção dos datasets `tbl_carteira_ibovespa` e `tbl_cotacao_ibovespa`.
* Tratamento dos dados da coluna `industria`.
* Transformação das colunas `date` em index do dataset.
* Criação de colunas de dados temporais a partir do index `Date`.
* Criação de colunas de transformação cíclica mensal e diário a partir do index `Date` a fim de preservar sua natureza periódica.
* Transformação do tipo de dado da coluna `Feriado`.
* Criação das colunas de diferenciação temporais a partir das colunas de performance diária `Open`, `High`, `Low`, `Close` e `Volume` para suavizar tendências e preparar o dado para modelagem temporal.
* Criação das colunas de lags temporais a partir das colunas de performance diária `Open`, `High`, `Low`, `Close` e `Volume` para capturar padrões de dependência temporal.
* Criação da colunas de análise técnica de momentum `rsi` e `macd`.
* Criação da colunas de análise técnica de momentum `rsi` e `macd`.
* Criação da colunas de análise técnica de força `retorno_diff_lag1_volume`.
* Criação da colunas target `Close_diff_t_plus_1` a partir do deslocamento da coluna `Close_diff`.

---

 **Remoção de valores**

* **Valores Nulos:** Filtragem dos valores nulos contidos no dataset: 7548 linhas com dados em colunas geradas por diferenciação ou lag.
* **Valores Duplicados:** Não há valores duplicados na base.

---

**Análise Gráfica**


* **Análise de estacionariedade da serie para definição de lags e médias móveis:**
    * Teste de estacionariedade do target com e sem diferenciação.
    * Gráfico e Decomposição de Série Temporal.
    * Gráfico boxplot dos dados escalonados.
    * Gráfico histograma e qq-plot da distribuição dos dados.
    * Gráfico AFC e PACF com diferenciação.
    * Gráfico Pairplot de features selecionadas com o target diferenciado.
    * Gráfico Heatmap de features selecionadas com o target diferenciado.
    * Análise VIF de features selecionadas com o target diferenciado.


---
**Seleção de colunas**
* Remoção de colunas.
* Renome de colunas.

---

**Requisitos para o Pipeline**

* **Recomendação de etapas:** `ColumnTransformer` + `Pipeline` + `OneHotEncoder` + `TargetEncoder`+`StandarScaler`.

## Setup

In [1]:
# carregamento das bibliotecas
import sys
import os
import pandas as pd
# Adiciona a pasta raiz do projeto (onde está a pasta src) ao sys.path
sys.path.append(os.path.abspath(os.path.join("..")))
from src.config.logging_config import setup_logging
from src.data.load_data import carregar_dataset
from src.data.preprocessing import *
from src.data.data_quality import *
from src.visualization.interactive_plot import *
from src.visualization.static_plot import *
from src.visualization.ts_test_plot import *
from src.utils.statistics import *

In [2]:
# configuração do logging
setup_logging()

## Carregamento dos dados

In [3]:
# carregamento da tabela de ações componentes do ibovespa com dados setorais
tbl_carteira_ibovespa = carregar_dataset(path='../data/external/tbl_acoes_ibovespa.csv')
tbl_carteira_ibovespa

2025-10-20 12:24:40,832 | INFO | src.data.load_data | Captura do arquivo csv no path:../data/external/tbl_acoes_ibovespa.csv

,codigo,tipo,empresa,slug,setor,industria
0,ABEV3,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
1,ALOS3,ON,Allos,alos3,Imóveis,Atividades Imobiliárias
2,ASAI3,ON,Assaí­ Atacadista,assai-asai3,Consumo não-cíclico,Varejo de alimentos e medicamentos
3,AURE3,ON,Auren,auren-energia-aure3,Utilidades,Empresas independentes e concessionárias elétr...
4,AZZA3,ON,Azzas 2154,azzas-2154-azza3,Consumo cíclico,Varejistas especializados
...,...,...,...,...,...,...
79,CPLE6,PNB,Companhia Paranaense de Energia COPEL,copel-pnb,Utilidades,Empresas independentes e concessionárias elétr...
80,TIMS3,ON,TIM SA,tim-part-s-a-on-nm,Tecnologia,Serviços de telecomunicação
81,VAMO3,ON,Grupo Vamos,grupo-vamos-sa,Industria,Serviços de frete e logística
82,VBBR3,ON,Vibra Energia SA,petrobras-distribuidora,Energia,Gás e Petróleo
83,VIVA3,ON,Vivara Participações SA,vivara-participacoes-sa,Consumo cíclico,Varejistas especializados

In [4]:
# carregamento da base histórica de ações componentes do ibovespa para validação dos dados
tbl_cotacao_ibovespa = carregar_dataset(path='../data/raw/tbl_acoes_ibovespa_historico_nova_rodada_2.csv', sep=',')
tbl_cotacao_ibovespa.tail()

2025-10-20 12:24:40,870 | INFO | src.data.load_data | Captura do arquivo csv no path:../data/raw/tbl_acoes_ibovespa_historico_nova_rodada_2.csv

,Date,ticker,Open,High,Low,Close,Volume,Dividends,Stock Splits,trailingPE,priceToBook,returnOnEquity,profitMargins,revenueGrowth,dividendYield,totalDebt,freeCashflow
40994,2025-07-17 00:00:00-03:00,VIVA3,25.309999,25.420000,24.969999,25.240000,1778200,0.0,0.0,10.066434,2.450422,0.27297,0.24285,0.16,2.37,1069810240,-372047808.0
40995,2025-07-18 00:00:00-03:00,VIVA3,24.990000,25.830000,24.430000,25.580000,8006800,0.0,0.0,10.066434,2.450422,0.27297,0.24285,0.16,2.37,1069810240,-372047808.0
40996,2025-07-21 00:00:00-03:00,VIVA3,25.580000,26.000000,25.290001,25.700001,4756700,0.0,0.0,10.066434,2.450422,0.27297,0.24285,0.16,2.37,1069810240,-372047808.0
40997,2025-07-22 00:00:00-03:00,VIVA3,25.730000,25.879999,24.790001,24.790001,3152000,0.0,0.0,10.066434,2.450422,0.27297,0.24285,0.16,2.37,1069810240,-372047808.0
40998,2025-07-23 00:00:00-03:00,VIVA3,24.700001,25.570000,24.420000,25.389999,1841600,0.0,0.0,10.066434,2.450422,0.27297,0.24285,0.16,2.37,1069810240,-372047808.0

## Feature Engineering

In [5]:
# junção dos dados setoriais com a tabela de cotação
tbl_cotacao_ibovespa = tbl_cotacao_ibovespa.merge(tbl_carteira_ibovespa, left_on='ticker', right_on='codigo', how='left')
tbl_cotacao_ibovespa.drop(columns='codigo', axis=1, inplace=True)
tbl_cotacao_ibovespa.head()

,Date,ticker,Open,High,Low,Close,Volume,Dividends,Stock Splits,trailingPE,...,profitMargins,revenueGrowth,dividendYield,totalDebt,freeCashflow,tipo,empresa,slug,setor,industria
0,2023-07-24 00:00:00-03:00,ABEV3,13.184119,13.314054,13.002209,13.097495,28477500,0.0,0.0,13.159574,...,0.16084,0.002,8.5,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
1,2023-07-25 00:00:00-03:00,ABEV3,13.201444,13.227431,12.811638,13.019534,25287600,0.0,0.0,13.159574,...,0.16084,0.002,8.5,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
2,2023-07-26 00:00:00-03:00,ABEV3,12.967560,13.036859,12.880936,12.976222,22007900,0.0,0.0,13.159574,...,0.16084,0.002,8.5,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
3,2023-07-27 00:00:00-03:00,ABEV3,12.950235,13.028196,12.716352,12.733676,24140400,0.0,0.0,13.159574,...,0.16084,0.002,8.5,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
4,2023-07-28 00:00:00-03:00,ABEV3,12.776989,12.993548,12.699027,12.958899,15430600,0.0,0.0,13.159574,...,0.16084,0.002,8.5,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas

In [6]:
# remoção das colunas fundamentalistas,pois elas geram uma repetição dos dados com a execução da api, não recuperando o histórico.
tbl_cotacao_ibovespa.drop(columns=['Dividends',
       'Stock Splits', 'trailingPE', 'priceToBook', 'returnOnEquity',
       'profitMargins', 'revenueGrowth', 'dividendYield', 'totalDebt',
       'freeCashflow'], axis=1, inplace=True)

In [7]:
# tratamento dos dados da coluna industria
tbl_cotacao_ibovespa.industria = tbl_cotacao_ibovespa.industria.str.lstrip()
tbl_cotacao_ibovespa.industria.value_counts()

industria
Empresas independentes e concessionárias elétricas         5987
Gás e Petróleo                                             3991
Metais e Mineração                                         3493
Serviços bancários                                         2994
Alimentos e tabaco                                         2495
Atvidades Imobiliárias                                     1996
Varejistas especializados                                  1996
Seguro                                                     1996
Varejo de alimentos e medicamentos                         1497
Prestação de serviços de Saúde                             1497
Serviços de hotel e entretenimento                          998
Serviços de frete e logística                               998
Serviços de telecomunicação                                 998
Colégio, faculdade e universidade                           998
Banco de investimento e serviços associados                 998
Atividades Imobiliárias                                     997
Infraestrutura de transportes                               563
Serviços de software e TI                                   499
Papel e Produtos Florestais                                 499
Automóveis e peças                                          499
Concessionárias de água e relacionados                      499
Serviços de transporte de passageiros                       499
Bebidas                                                     499
Varejo diversificado                                        499
Contêineres e Embalagens                                    499
Produtos farmacêuticos                                      499
Transporte Espacial e Defesa                                499
Conglomerados de bens de consumo                            499
Químicos                                                    499
Máquinas, Ferramentas, veículos pesados, trens e navios     499
Serviços e produtos pessoais e domésticos                    20
Name: count, dtype: int64

In [8]:
# transformação da coluna date em index do dataset
tbl_cotacao_ibovespa.set_index('Date', drop=True, inplace=True)
tbl_cotacao_ibovespa.index = pd.to_datetime(tbl_cotacao_ibovespa.index)

In [9]:
# informações da tabela
tbl_cotacao_ibovespa.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 40999 entries, 2023-07-24 00:00:00-03:00 to 2025-07-23 00:00:00-03:00
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticker     40999 non-null  object
 1   Open       40999 non-null  float64
 2   High       40999 non-null  float64
 3   Low        40999 non-null  float64
 4   Close      40999 non-null  float64
 5   Volume     40999 non-null  int64
 6   tipo       40999 non-null  object
 7   empresa    40999 non-null  object
 8   slug       40999 non-null  object
 9   setor      40999 non-null  object
 10  industria  40999 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 3.8+ MB

In [10]:
# verificação da quantidade de ações por industria
empresas_por_industria = agrupar_dados(df=tbl_cotacao_ibovespa, cols_agrup=['setor', 'industria'], cols_filter=['ticker'], agr='nunique').reset_index()
empresas_por_industria.head()

2025-10-20 12:24:41,221 | INFO | src.data.preprocessing | Agrupamento selecionado: ['setor', 'industria'], filtragem dataset:['ticker'], método: nunique

                  setor                           industria  ticker
0       Consumo cíclico                  Automóveis e peças       1
1       Consumo cíclico  Serviços de hotel e entretenimento       2
2       Consumo cíclico           Varejistas especializados       3
3       Consumo cíclico                Varejo diversificado       1
4   Consumo não-cíclico                  Alimentos e tabaco       5

In [11]:
# verificação da quantidade de categorias por setor
industrias_por_setor = tbl_cotacao_ibovespa.groupby('setor')['industria'].nunique().reset_index(name='count_categ_industria')
industrias_por_setor

                                  setor  count_categ_industria
0                       Consumo cíclico                      4
1                   Consumo não-cíclico                      5
2                            Financeiro                      3
3                     Materiais básicos                      4
4                                 Saúde                      2
5    Serviços acadêmicos e educacionais                      1
6                            Tecnologia                      2
7                       Consumo cíclico                      1
8                               Energia                      1
9                            Financeiro                      1
10                              Imóveis                      2
11                            Industria                      5
12                           Industrias                      1
13                           Tecnologia                      1
14                           Utilidades                      2

In [12]:
# verificação da quantidade de ações por setor
empresas_por_setor = tbl_cotacao_ibovespa.groupby(['setor'])['ticker'].nunique().reset_index(name='count_acoes_setor')
empresas_por_setor.head()

                  setor  count_acoes_setor
0       Consumo cíclico                  7
1   Consumo não-cíclico                 11
2            Financeiro                 10
3     Materiais básicos                 10
4                 Saúde                  4

In [13]:
# inserção de dados temporais no dataset
tbl_cotacao_ibovespa = dados_temporais(df=tbl_cotacao_ibovespa)
tbl_cotacao_ibovespa.head()

,ticker,Open,High,Low,Close,Volume,tipo,empresa,slug,setor,industria,dayofweek,month,Feriado
Date,,,,,,,,,,,,,,
2023-07-24 00:00:00-03:00,ABEV3,13.184119,13.314054,13.002209,13.097495,28477500,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,0,7,False
2023-07-25 00:00:00-03:00,ABEV3,13.201444,13.227431,12.811638,13.019534,25287600,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,1,7,False
2023-07-26 00:00:00-03:00,ABEV3,12.967560,13.036859,12.880936,12.976222,22007900,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,2,7,False
2023-07-27 00:00:00-03:00,ABEV3,12.950235,13.028196,12.716352,12.733676,24140400,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,3,7,False
2023-07-28 00:00:00-03:00,ABEV3,12.776989,12.993548,12.699027,12.958899,15430600,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,4,7,False

In [14]:
# transformação cíclica para dias uteis 
tbl_cotacao_ibovespa = transformacao_ciclica(df=tbl_cotacao_ibovespa, dias_uteis=True)

2025-10-20 12:24:41,711 | INFO | src.data.preprocessing | Transformação cíclica com dias úteis para as colunas de dados temporais.

In [15]:
# transformação da colunas Feriado no formato int
tbl_cotacao_ibovespa['Feriado'] = tbl_cotacao_ibovespa['Feriado'].astype(int)

In [16]:
# gerar diferenciação do target para revalidar a estacionariedade da serie
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Close')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Volume')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Open')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='High')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Low')

In [17]:
# inserção das colunas de janela para o target e colunas de performance da ação
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Close_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Volume_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Open_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='High_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Low_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Close')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Open')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='High')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Low')

**Features de análise técnica**<br>
O indicadores rsi, macd e retorno_diff_lag1_volume conseguem captar a variabilidade e o momentum temporal das ações.<br>
Juntas, elas oferecem uma visão robusta da dinâmica de mercado, cobrindo extremos de preço (RSI), direção da tendência (MACD) e força da participação (Volume).

In [18]:
# construção da coluna rsi para captar o extremo da variação
tbl_cotacao_ibovespa['rsi'] = calcular_rsi(tbl_cotacao_ibovespa)

In [19]:
# construção da coluna macd para captar a direção e força da tendência
tbl_cotacao_ibovespa['macd'], tbl_cotacao_ibovespa['macd_signal'] = calcular_macd(tbl_cotacao_ibovespa)

In [20]:
# construção da coluna rsi para captar a liquidez da ação
tbl_cotacao_ibovespa['retorno_diario_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['Volume'].pct_change()
tbl_cotacao_ibovespa['retorno_diff_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diario_volume'].diff()
tbl_cotacao_ibovespa['retorno_diff_lag1_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diff_volume'].shift(1)
tbl_cotacao_ibovespa = tbl_cotacao_ibovespa.drop(columns=['retorno_diario_volume', 'retorno_diff_volume'])

**Modificação do target**<br>
Nosso objetivo é prever o **Retorno Diário de Amanhã** ($\mathbf{\text{Close\_diff}_{t+1}}$).
Para garantir a validade do modelo e evitar **_Data Leakage_**, aplicamos um **deslocamento (`shift(-1)`)** no `Close_diff`.<br>
Esta ação **alinha o Target futuro** ($\mathbf{t+1}$) com todas as **Features conhecidas hoje** ($\mathbf{t}$), simulando o cenário real de previsão de mercado:
$$\mathbf{\text{Features}_t \rightarrow \text{Target}_{t+1}}$$

In [21]:
# transformação do target para previsao 
tbl_cotacao_ibovespa['Close_diff_t_plus_1'] = tbl_cotacao_ibovespa['Close_diff'].shift(-1)
tbl_cotacao_ibovespa['Close_t_plus_1'] = tbl_cotacao_ibovespa['Close'].shift(-1)

In [22]:
# visualização do deslocamento do target para previsão
tbl_cotacao_ibovespa[['Close','Close_t_plus_1','Close_diff','Close_diff_t_plus_1']].head()

,Close,Close_t_plus_1,Close_diff,Close_diff_t_plus_1
Date,,,,
2023-07-24 00:00:00-03:00,13.097495,13.019534,NaN,-0.077961
2023-07-25 00:00:00-03:00,13.019534,12.976222,-0.077961,-0.043312
2023-07-26 00:00:00-03:00,12.976222,12.733676,-0.043312,-0.242546
2023-07-27 00:00:00-03:00,12.733676,12.958899,-0.242546,0.225223
2023-07-28 00:00:00-03:00,12.958899,12.872273,0.225223,-0.086625

## Verificação de Nulos

In [23]:
# verificação de nulos
verificacao_nulos(tbl_cotacao_ibovespa).sort_values(ascending=False)

volatility_360_Open_diff             29686
volatility_360_Low_diff              29686
lag_360_Open_diff                    29686
retorno_acumulado_360_Volume_diff    29686
volatility_360_Volume_diff           29686
                                     ...
Feriado                                  0
day_sin                                  0
day_cos                                  0
month_sin                                0
ticker                                   0
Length: 398, dtype: int64

In [24]:
# remoção de linhas nulas para análise descritiva temporal
tbl_cotacao_ibovespa.dropna(inplace=True)

## Verificação de duplicados
Com a filtragem de linhas verifica-se que apesar da repetição de valores iguais de abertura, fechamento, mínimo e máximo no dataset em diversos index, não há repetição, pois pode haver constância nos valores do preço de uma ação.

In [25]:
# verificação de duplicados
index_duplicados = tbl_cotacao_ibovespa.duplicated(keep=False)
tbl_cotacao_ibovespa.loc[index_duplicados]

Empty DataFrame
Columns: [ticker, Open, High, Low, Close, Volume, tipo, empresa, slug, setor, industria, dayofweek, month, Feriado, day_sin, day_cos, month_sin, month_cos, Close_diff, Volume_diff, Open_diff, High_diff, Low_diff, lag_1_Close_diff, lag_3_Close_diff, lag_5_Close_diff, lag_7_Close_diff, lag_15_Close_diff, lag_30_Close_diff, lag_60_Close_diff, lag_90_Close_diff, lag_120_Close_diff, lag_180_Close_diff, lag_360_Close_diff, rolling_mean_3_Close_diff, volatility_3_Close_diff, retorno_acumulado_3_Close_diff, rolling_mean_5_Close_diff, volatility_5_Close_diff, retorno_acumulado_5_Close_diff, rolling_mean_7_Close_diff, volatility_7_Close_diff, retorno_acumulado_7_Close_diff, rolling_mean_15_Close_diff, volatility_15_Close_diff, retorno_acumulado_15_Close_diff, rolling_mean_30_Close_diff, volatility_30_Close_diff, retorno_acumulado_30_Close_diff, rolling_mean_60_Close_diff, volatility_60_Close_diff, retorno_acumulado_60_Close_diff, rolling_mean_90_Close_diff, volatility_90_Close_diff, retorno_acumulado_90_Close_diff, rolling_mean_120_Close_diff, volatility_120_Close_diff, retorno_acumulado_120_Close_diff, rolling_mean_180_Close_diff, volatility_180_Close_diff, retorno_acumulado_180_Close_diff, rolling_mean_360_Close_diff, volatility_360_Close_diff, retorno_acumulado_360_Close_diff, lag_1_Volume_diff, lag_3_Volume_diff, lag_5_Volume_diff, lag_7_Volume_diff, lag_15_Volume_diff, lag_30_Volume_diff, lag_60_Volume_diff, lag_90_Volume_diff, lag_120_Volume_diff, lag_180_Volume_diff, lag_360_Volume_diff, rolling_mean_3_Volume_diff, volatility_3_Volume_diff, retorno_acumulado_3_Volume_diff, rolling_mean_5_Volume_diff, volatility_5_Volume_diff, retorno_acumulado_5_Volume_diff, rolling_mean_7_Volume_diff, volatility_7_Volume_diff, retorno_acumulado_7_Volume_diff, rolling_mean_15_Volume_diff, volatility_15_Volume_diff, retorno_acumulado_15_Volume_diff, rolling_mean_30_Volume_diff, volatility_30_Volume_diff, retorno_acumulado_30_Volume_diff, rolling_mean_60_Volume_diff, volatility_60_Volume_diff, retorno_acumulado_60_Volume_diff, rolling_mean_90_Volume_diff, volatility_90_Volume_diff, retorno_acumulado_90_Volume_diff, rolling_mean_120_Volume_diff, volatility_120_Volume_diff, retorno_acumulado_120_Volume_diff, rolling_mean_180_Volume_diff, ...]
Index: []

[0 rows x 398 columns]

## Análise Gráfica

### Análise de estacionariedade da serie para definição de lags e médias móveis<br>
Aplicando a diferenciação de primeira ordem NA série temporal conseguimos reduzir o ruído e concentrar os valores em um intervalo conhecido, ou seja, estacionário.<br>
Esta transformação é o passo inicial que viabiliza a aplicação de modelos tradicionais de séries temporais e permite que a análise dos gráficos FAC/PAFC (Autocorrelação).<br>
Validamos estatisticamente essa transformação por meio do Teste de Dickey-Fuller Aumentado (ADF) e confirmamos pela análise gráfica da decomposição da série (que mostrou a redução de tendência para a maioria das ações).

In [26]:
# teste de estacionariedade
teste_estacionariedade_interativo(df= tbl_cotacao_ibovespa, coluna_valor = 'Close')
teste_estacionariedade_interativo(df= tbl_cotacao_ibovespa, coluna_valor = 'Close_diff_t_plus_1')

interactive(children=(Dropdown(description='ticker', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

HTML(value='\n        <p>🔍 <strong>Teste ADF - Close | Ticker: ABEV3</strong></p>\n        <ul>\n            <…

interactive(children=(Dropdown(description='ticker', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

HTML(value='\n        <p>🔍 <strong>Teste ADF - Close_diff_t_plus_1 | Ticker: ABEV3</strong></p>\n        <ul>\…

In [27]:
# análise da serie não-diferenciada e decomposicao da série temporal diferenciada
grafico_lineplot(df=tbl_cotacao_ibovespa, x_col=tbl_cotacao_ibovespa.index, 
                 y_col='Close', interativo=True, cat_col='ticker',
                 titulo='Gráfico de série temporal pela feature')

grafico_decomposicao_temporal(df= tbl_cotacao_ibovespa, target = 'Close_diff_t_plus_1', period=5, interativo=True, cat_col='ticker')

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

**Seleção de features para análise**<br>
Como há uma alta quantidade de features, selecionei as mais correlacionadas com o target para validar o impacto.<br>
Isso não substitui o processo de seleção de features na seleção de modelos.

In [28]:
# seleção das features mais correlacionadas para análise do target 
df = tbl_cotacao_ibovespa.select_dtypes(include='number').resample('D').mean()
target_feature = 'Close_diff_t_plus_1' 

correlacoes = df.corr()[target_feature].sort_values(ascending=False)
features =correlacoes.abs().nlargest(10).index.to_list()+ ['ticker']

**Permanência de Outliers**<br>
Como estamos lidando com dados de performance de ações, não podemos remover valores extremos sem impactar a performance de predição.<br>
Portanto, o escolhi aplicar uma escalonamento simples para validar o processo.<br>
Analisando as ações, percebemos que essa transformação simples consegue manter um intervalo de valores menor que 7 desvios<br>
Para modelos em árvore não temos essa necessidade, mas pela alta esparcidade dos dados, optei por seguir come essa técnica.

In [29]:
# análise boxplot interativa dos com escalonemanto dados 
grafico_boxplot(tbl_cotacao_ibovespa[features], cat_col='ticker', scaler=True, interativo=True)

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

**Proximidade com a distribuição normal**<br>
Ao aplicar o QQ-Plot (Quantile-Quantile Plot) nas *features* diferenciadas, observamos que, para a maioria dos ativos, o corpo central da amostra de dados apresenta uma forte proximidade com os quantis da distribuição normal teórica.<br>
A concentração de variação nos extremos, formando "caudas pesadas" (um comportamento esperado para séries de retornos financeiros), é mantida.<br>
Essa proximidade com a normalidade no centro da distribuição favorece a robustez e a previsibilidade do modelo, especialmente para a maioria dos eventos de mercado.<br>

In [30]:
# histograma do target com escala
grafico_qq_plot(df=tbl_cotacao_ibovespa[features], 
                   feature='ticker', interativo=True,
           )

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

**Dependência Temporal**<br>
A maioria dos *lags* está **dentro do intervalo de confiança**, confirmando que a diferenciação foi eficaz e que os retornos se aproximam de um processo de Passeio Aleatório (*Random Walk*).
* **ACF:** Apresenta algumas autocorrelações significativas estendendo-se até o lag 10.
* **PACF:** Demonstra picos significativos nos primeiros lags (próximo ao lag 4) e também em lags mais distantes (maior que 8).

A presença de correlação direta na PAFC no lag 4 (e em lags maiores) indica que a série retém uma memória de curto e médio prazo. Isso sugere que modelos mais complexos que incluam componentes **Autorregressivos (AR)**, com ordem **p** capaz de capturar a dependência no lag 4 e no lag 8, devem ser explorados para a fase de previsão.

In [31]:
# gráfico de autocorrelacao para definição do número de lags e médias móveis
grafico_acf_interativo(df=tbl_cotacao_ibovespa,coluna_valor = 'Close_diff_t_plus_1',max_lags=30)

VBox(children=(Dropdown(description='Ticker:', layout=Layout(width='300px'), options=('ABEV3', 'ALOS3', 'ASAI3…

In [32]:
# gráfico de autocorrelacao parcial para definição do número de lags e médias móveis
grafico_pacf_interativo(df=tbl_cotacao_ibovespa,coluna_valor = 'Close_diff_t_plus_1',max_lags=9)

VBox(children=(Dropdown(description='Ação:', layout=Layout(width='300px'), options=('ABEV3', 'ALOS3', 'ASAI3',…

**Baixa tendência das features selecionadas**<br>
Apesar de terem a maior correlação linear estatística com o Target (identificada por métodos numéricos), as *features* não demonstram uma tendência visualmente concentrada nos gráficos de dispersão (os pontos estão bastante dispersos).<br>
Essa dispersão é típica em dados de retornos financeiros, onde a relação entre variáveis raramente é uma linha reta perfeita.<br>
A baixa concentração visual não invalida o uso dessas *features*. Esperamos que o modelo de *Machine Learning*, especialmente modelos de árvores.<br>

In [33]:
# análise de correlação das features com o target
grafico_pairplot_target(df=tbl_cotacao_ibovespa, target='Close_diff_t_plus_1', 
                        lista_features=features,interativo=True, cat_col='ticker')

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

In [34]:
# análise de correlação das features com o target
df = tbl_cotacao_ibovespa.copy()
encoding = pd.get_dummies(df[['tipo', 'setor', 'industria']])
df = pd.concat([df, encoding], axis=1)


grafico_heatmap(df[features], 
 interativo=True, feature='ticker')

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

**Inflação das features semelhantes**<br>
Como selecionamos as features de maior correlação para análise, percebemos que há um alto valor de inflação da variância nas features do mesmo período para os indicadores.<br>
Para os demais indicadores percebemos um baixo valor, o que justifica a independência e garantia de previsibilidade das features.

In [35]:
# análise vif
analise_vif(tbl_cotacao_ibovespa[features],interativo=True, feature='ticker')

interactive(children=(Dropdown(description='valor', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3S…

# Seleção de colunas

In [36]:
# remoção de colunas para gerar dataset para validação de modelos
tbl_cotacao_ibovespa.drop(columns=['empresa','slug','Feriado', 'month','dayofweek', 'Low','High',], axis=1, inplace=True)

In [37]:
# renome das colunas para treinamento do modelo
dicionario = {"ticker":"ticker",
       "Close_diff":"close_diff",
       'Close_t_plus_1':'close_t_plus_1',
       "Close_diff_t_plus_1":"close_diff_t_plus_1",
       "lag_1_Close_diff":"lag_1_close_diff",
       "lag_2_Close_diff":"lag_2_close_diff", 
       "lag_3_Close_diff":"lag_3_close_diff",
       "lag_5_Close_diff":"lag_5_close_diff",
       "rolling_mean_3_Close_diff":"rolling_mean_3_close_diff",
       "volatility_3_Close_diff":"volatility_3_close_diff",
       "retorno_acumulado_3_Close_diff":"retorno_acumulado_3_close_diff",
       "rolling_mean_5_Close_diff":"rolling_mean_5_close_diff",
       "volatility_5_Close_diff":"volatility_5_close_diff", 
       "retorno_acumulado_5_Close_diff":"retorno_acumulado_5_close_diff"}
tbl_cotacao_ibovespa.rename(columns=dicionario, inplace=True)

In [38]:
# salvar o dataset para treino e validação dos modelos
tbl_cotacao_ibovespa.to_csv('../data/processed/tbl_cotacao_ibovespa_processed.csv', index=True)

# Requisitos para o Pipeline

### Variáveis Numéricas

- **Escalonamento**: Algumas colunas apresentam escalas muito distintas (ex: valores monetários vs. proporções decimais). Será aplicado `StandardScaler` para uniformizar a amplitude das variáveis e facilitar o aprendizado dos modelos.

---

### Variáveis Categóricas

- **Codificação (Encoding)**: 
  - Será utilizado *One-Hot Encoding* para variáveis com baixo número de categorias, garantindo interpretabilidade e boa performance nos modelos.
  - Aplicação de *Target Encoding* simples para a variável `acao`, devido ao número elevado de categorias e distribuição balanceada entre elas. Essa abordagem permite capturar a relação estatística entre a variável categórica e o target sem aumentar excessivamente a dimensionalidade.