
---

**Análise Exploratória de Dados (EDA) - Amazon Last-Mile**

Esse documento consiste em uma análise exploratória dos dados de operação de transporte last-mile da Amazon - Índia. A base de dados inclui 43 mil registros de dados, incluindo informações de geolocalização, detalhes do pedido, entregador, condições de tempo e tráfego, e métrica de performance.

**Target**

* Identificar padrões para a predição do **order_cicle_time** (tempo total do pedido), KPI de performance de mercado identificado como OTD (On-time-delivery).
* **OTD:** Entregas realizadas no SLA (tempo mínimo de 2 horas). Medido desde a entrada do pedido no sistema até o destino final do cliente.

---

 **Feature Engineering**

 **Feature Transformation**

* Transformação do tipo de dado das colunas `Order_Date`, `Order_Time` e `Pickup_Time` para o formato `datetime`.
* Correção de dados de geolocalização negativos.
* Filtragem de dados de geolocalização.
* Tratamento de caracteres da coluna `Traffic`,`Area`, `Weather` e `Vehicle` .

 **Feature Extraction**

* Criação de colunas de dados temporais para a feature `Order_Date` para remoção da temporalidade dos dados.
* Criação de colunas de transformação cíclica mensal e diário para a feature `Order_Date` para remoção da temporalidade dos dados.
* Criação das colunas `pickup_duration` entre a diferença de tempo entre `Order_Time` e `Pickup_Time`.
* Criação da coluna target `order_cicle_time`: soma da coluna `pickup_duration` e `Delivery_Time`.
* Criação da coluna de `delivery_distance` a partir dos dados geolocalizados da loja à residência do cliente.
* Criação de coluna `dist_gte_10` para redução do ruído causado pela distribuição dos valores contínuos de `delivery_distance`.
* Criação da coluna `is_grocery` resultante da etapa de teste de hipóteses, onde se identificou uma performance de `order_cicle_time` inferior às demais categorias.
* Criação da coluna `jam_or_high_traffic` resultante da etapa de teste de hipóteses, onde se identificou uma performance de `order_cicle_time` maior às demais categorias de Traffic.
* Criação da coluna `is_sunny_weather` resultante da etapa de teste de hipóteses, onde se identificou uma performance de `order_cicle_time` inferior às demais categorias de Weather.


---

 **Remoção de valores**

* **Valores Nulos:** Filtragem dos valores nulos contidos no dataset: 145 linhas com dados nas colunas `Agent_Rating`, `Order_Time`, `Pickup_Time`, `pickup_duration`.
* **Valores Duplicados:** Não há valores duplicados na base.

---

**Dataset `tbl_amazon_dlv_eda`**

*(Processos em cópia para evitar data_leakage para a base de treino do modelo)*

* **Validação Encoding:** Aplicação de One-Hot Encoding nas colunas `Weather`, `Vehicle`, `Traffic` e `Area`.
* **Validação Discretização:** Construção de classes nas colunas `Agent_Rating` e `Agent_Age`.
* **Validação de Transformação e Escalonamento:**
    * Aplicação de transformação Yeo-Johnson nas colunas numéricas.
    * Aplicação de escalonamento com `StandardScaler` nas colunas numéricas.
* **Validação Remoção de Outliers:** Aplicação da função IQR para manter os dados em até 3 desvios para a coluna `Agent_Rating`.

---

**Testes de Hipótese e Insights**

* **Definição de uma política de performance** para o indicador OTD a ser avaliado através de simulação com a lib Simpy.
* **Gráfico de distribuição e pairplot** para análise da distribuição do target.
* **Gráfico Heatmap** para análise de correlação das features no target `order_cicle_time`.
* **Análise VIF** para mensuração de multicolinearidade das features.

**Hipóteses Validadas**

* **Teste ANOVA:** A média de `order_cicle_time` é diferente para as condições de tráfego da coluna `Traffic`.
* **Teste ANOVA:** O efeito do tráfego no tempo de entrega não é o mesmo para todos os tipos de clima.
* **Teste ANOVA e Tukey (complementar):** A média de `order_cicle_time` é diferente para cada uma das categorias da coluna `Category`.
* **Teste ANOVA e Tukey (complementar):** A média de `order_cicle_time` é diferente para as condições de tempo da coluna `Weather`.
* **Teste-t duas amostras:** A média de `order_cicle_time` é diferente para as condições de tempo da coluna `holiday`.

---

**Requisitos para o Pipeline**

* **Recomendação de etapas:** `ColumnTransformer` + `Pipeline` + `IQRDetectorClip` + `KBinsDicretizer`.

---

**Dataset para Treinamento**

* Descrição das features da `tbl_amazon_dlv` usadas na etapa de treino e validação do modelo.

# Análise Exploratória de Dados

## Setup

In [1]:
# carregamento das bibliotecas
import sys
import os
import pandas as pd
# Adiciona a pasta raiz do projeto (onde está a pasta src) ao sys.path
sys.path.append(os.path.abspath(os.path.join("..")))
from src.config.logging_config import setup_logging
from src.data.load_data import carregar_dataset
from src.data.preprocessing import *
from src.data.data_quality import *
from src.visualization.interactive_plot import *
from src.visualization.static_plot import *
from src.visualization.ts_test_plot import *

In [2]:
# configuração do logging
setup_logging()

## Carregamento dos dados

In [3]:
# carregamento da tabela de ações componentes do ibovespa com dados  setorais
tbl_carteira_ibovespa = carregar_dataset(path='../data/external/tbl_acoes_ibovespa.csv')
tbl_carteira_ibovespa

2025-10-14 19:23:37,971 | INFO | src.data.load_data | Captura do arquivo csv no path:../data/external/tbl_acoes_ibovespa.csv

,codigo,tipo,empresa,slug,setor,industria,ticker
0,ABEV3,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,ABEV3.SA
1,ALOS3,ON,Allos,alos3,Imóveis,Atividades Imobiliárias,ALOS3.SA
2,ASAI3,ON,Assaí­ Atacadista,assai-asai3,Consumo não-cíclico,Varejo de alimentos e medicamentos,ASAI3.SA
3,AURE3,ON,Auren,auren-energia-aure3,Utilidades,Empresas independentes e concessionárias elétr...,AURE3.SA
4,AZZA3,ON,Azzas 2154,azzas-2154-azza3,Consumo cíclico,Varejistas especializados,AZZA3.SA
...,...,...,...,...,...,...,...
79,CPLE6,PNB,Companhia Paranaense de Energia COPEL,copel-pnb,Utilidades,Empresas independentes e concessionárias elétr...,CPLE6.SA
80,TIMS3,ON,TIM SA,tim-part-s-a-on-nm,Tecnologia,Serviços de telecomunicação,TIMS3.SA
81,VAMO3,ON,Grupo Vamos,grupo-vamos-sa,Indústria,Serviços de frete e logística,VAMO3.SA
82,VBBR3,ON,Vibra Energia SA,petrobras-distribuidora,Energia,Gás e Petróleo,VBBR3.SA
83,VIVA3,ON,Vivara Participações SA,vivara-participacoes-sa,Consumo cíclico,Varejistas especializados,VIVA3.SA

In [4]:
# carregamento da base historica de ações componentes do ibovespa para validação dos dados
tbl_cotacao_ibovespa = carregar_dataset(path='../data/raw/tbl_acoes_ibovespa_historico_nova_rodada.csv', sep=',')
tbl_cotacao_ibovespa.tail()

2025-10-14 19:23:37,995 | INFO | src.data.load_data | Captura do arquivo csv no path:../data/raw/tbl_acoes_ibovespa_historico_nova_rodada.csv

,Date,ticker,Open,High,Low,Close,Volume,Dividends,Stock Splits,trailingPE,priceToBook,returnOnEquity,profitMargins,revenueGrowth,dividendYield,totalDebt,freeCashflow
19761,2025-07-18 00:00:00-03:00,VIVA3,24.990000,25.830000,24.430000,25.580000,8006800,0.0,0.0,8.745981,2.447804,0.31979,0.27443,0.208,2.44,1063061696,-336666272.0
19762,2025-07-21 00:00:00-03:00,VIVA3,25.580000,26.000000,25.290001,25.700001,4756700,0.0,0.0,8.745981,2.447804,0.31979,0.27443,0.208,2.44,1063061696,-336666272.0
19763,2025-07-22 00:00:00-03:00,VIVA3,25.730000,25.879999,24.790001,24.790001,3152000,0.0,0.0,8.745981,2.447804,0.31979,0.27443,0.208,2.44,1063061696,-336666272.0
19764,2025-07-23 00:00:00-03:00,VIVA3,24.700001,25.570000,24.420000,25.389999,1841600,0.0,0.0,8.745981,2.447804,0.31979,0.27443,0.208,2.44,1063061696,-336666272.0
19765,2025-07-24 00:00:00-03:00,VIVA3,25.080000,25.350000,24.910000,25.049999,1806600,0.0,0.0,8.745981,2.447804,0.31979,0.27443,0.208,2.44,1063061696,-336666272.0

## Feature Engineering

In [5]:
# concatenação dos dados setoriais com a tabela de cotação
tbl_cotacao_ibovespa = tbl_cotacao_ibovespa.merge(tbl_carteira_ibovespa.drop(['ticker'], axis=1), left_on='ticker', right_on='codigo', how='left')
tbl_cotacao_ibovespa.drop(columns='codigo', axis=1, inplace=True)
tbl_cotacao_ibovespa.head()

,Date,ticker,Open,High,Low,Close,Volume,Dividends,Stock Splits,trailingPE,...,profitMargins,revenueGrowth,dividendYield,totalDebt,freeCashflow,tipo,empresa,slug,setor,industria
0,2024-08-07 00:00:00-03:00,ABEV3,11.231811,11.687784,11.203895,11.641256,48591300,0.0,0.0,13.297873,...,0.16084,0.002,7.47,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
1,2024-08-08 00:00:00-03:00,ABEV3,11.594729,11.687785,11.455146,11.501673,28173200,0.0,0.0,13.297873,...,0.16084,0.002,7.47,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
2,2024-08-09 00:00:00-03:00,ABEV3,11.576117,11.613339,11.455145,11.585423,19122000,0.0,0.0,13.297873,...,0.16084,0.002,7.47,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
3,2024-08-12 00:00:00-03:00,ABEV3,11.631950,11.678478,11.529590,11.529590,17501300,0.0,0.0,13.297873,...,0.16084,0.002,7.47,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas
4,2024-08-13 00:00:00-03:00,ABEV3,11.604034,11.780839,11.548200,11.697089,30082000,0.0,0.0,13.297873,...,0.16084,0.002,7.47,3157764096,1.793802e+10,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas

In [6]:
# nova iteração: remoção das colunas fundamentalistas,pois elas geram uma repetição dos dados com a execução da api, não recuperando o histórico
tbl_cotacao_ibovespa.drop(columns=['Dividends',
       'Stock Splits', 'trailingPE', 'priceToBook', 'returnOnEquity',
       'profitMargins', 'revenueGrowth', 'dividendYield', 'totalDebt',
       'freeCashflow'], axis=1, inplace=True)

In [7]:
# tratamento dos dados da coluna industria
tbl_cotacao_ibovespa.industria = tbl_cotacao_ibovespa.industria.str.lstrip()
tbl_cotacao_ibovespa.industria.value_counts()

industria
Empresas independentes e concessionárias elétricas        2880
Gás e Petróleo                                            1920
Metais e Mineração                                        1680
Serviços bancários                                        1440
Alimentos e tabaco                                        1200
Atvidades Imobiliárias                                     960
Varejistas especializados                                  960
Seguro                                                     960
Varejo de alimentos e medicamentos                         720
Prestação de serviços de Saúde                             720
Serviços de hotel e entretenimento                         480
Serviços de frete e logística                              480
Atividades Imobiliárias                                    480
Serviços de telecomunicação                                480
Colégio, faculdade e universidade                          480
Banco de investimento e serviços associados                480
Infraestrutura de transportes                              305
Serviços de software e TI                                  240
Papel e Produtos Florestais                                240
Automóveis e peças                                         240
Concessionárias de água e relacionados                     240
Serviços de transporte de passageiros                      240
Bebidas                                                    240
Varejo diversificado                                       240
Contêineres e Embalagens                                   240
Produtos farmacêuticos                                     240
Transporte Espacial e Defesa                               240
Conglomerados de bens de consumo                           240
Químicos                                                   240
Máquinas,Ferramentas, veículos pesados, trens e navios     240
Serviços e produtos pessoais e domésticos                   21
Name: count, dtype: int64

In [8]:
# transformação da coluna date em index do dataset
tbl_cotacao_ibovespa.set_index('Date', drop=True, inplace=True)
tbl_cotacao_ibovespa.index = pd.to_datetime(tbl_cotacao_ibovespa.index)

### Exploração

In [9]:
# informações da tabela
tbl_cotacao_ibovespa.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19766 entries, 2024-08-07 00:00:00-03:00 to 2025-07-24 00:00:00-03:00
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticker     19766 non-null  object
 1   Open       19766 non-null  float64
 2   High       19766 non-null  float64
 3   Low        19766 non-null  float64
 4   Close      19766 non-null  float64
 5   Volume     19766 non-null  int64
 6   tipo       19766 non-null  object
 7   empresa    19766 non-null  object
 8   slug       19766 non-null  object
 9   setor      19766 non-null  object
 10  industria  19766 non-null  object
dtypes: float64(4), int64(1), object(6)
memory usage: 1.8+ MB

In [10]:
# verificação de nulos
verificacao_nulos(tbl_cotacao_ibovespa)

ticker       0
Open         0
High         0
Low          0
Close        0
Volume       0
tipo         0
empresa      0
slug         0
setor        0
industria    0
dtype: int64

In [11]:
# verificação da quantidade de ações por industria
empresas_por_industria = agrupar_dados(df=tbl_cotacao_ibovespa, cols_agrup=['setor', 'industria'], cols_filter=['ticker'], agr='nunique').reset_index()
empresas_por_industria.head()

2025-10-14 19:23:38,183 | INFO | src.data.preprocessing | Agrupamento selecionado: ['setor', 'industria'], filtragem dataset:['ticker'], método: nunique

,setor,industria,ticker
0,Saúde,Prestação de serviços de Saúde,1
1,Serviços acadêmicos e educacionais,"Colégio, faculdade e universidade",1
2,Consumo cíclico,Automóveis e peças,1
3,Consumo cíclico,Serviços de hotel e entretenimento,2
4,Consumo cíclico,Varejistas especializados,4

In [12]:
industrias_por_setor = tbl_cotacao_ibovespa.groupby('setor')['industria'].nunique().reset_index(name='count_categ_industria')
industrias_por_setor

                                  setor  count_categ_industria
0                                 Saúde                      1
1    Serviços acadêmicos e educacionais                      1
2                       Consumo cíclico                      4
3                   Consumo não-cíclico                      5
4                               Energia                      1
5                            Financeiro                      3
6                               Imóveis                      2
7                             Indústria                      5
8                     Materiais básicos                      4
9                                 Saúde                      2
10   Serviços acadêmicos e educacionais                      1
11                           Tecnologia                      2
12                           Utilidades                      2

In [13]:
# verificação da quantidade de ações por setor
empresas_por_setor = tbl_cotacao_ibovespa.groupby(['setor'])['ticker'].nunique().reset_index(name='count_acoes_setor')
empresas_por_setor.head()

                                 setor  count_acoes_setor
0                                Saúde                  1
1   Serviços acadêmicos e educacionais                  1
2                      Consumo cíclico                  8
3                  Consumo não-cíclico                 11
4                              Energia                  8

## Verificação de duplicados
Com a filtragem de linhas verifica-se que apesar da repetição de valores iguais de abertura, fechamento, mínimo e máximo no dataset em diversos index, não há repetição, pois pode haver constância nos valores do preço de uma ação.

In [14]:
# verificação de duplicados
index_duplicados = tbl_cotacao_ibovespa.duplicated(keep=False)
tbl_cotacao_ibovespa.loc[index_duplicados]

,ticker,Open,High,Low,Close,Volume,tipo,empresa,slug,setor,industria
Date,,,,,,,,,,,
2025-06-26 00:00:00-03:00,NATU3,36.860001,36.860001,36.860001,36.860001,0,ON,Natura,natura-ntco3,Consumo não-cíclico,Serviços e produtos pessoais e domésticos
2025-06-27 00:00:00-03:00,NATU3,36.860001,36.860001,36.860001,36.860001,0,ON,Natura,natura-ntco3,Consumo não-cíclico,Serviços e produtos pessoais e domésticos
2025-06-30 00:00:00-03:00,NATU3,36.860001,36.860001,36.860001,36.860001,0,ON,Natura,natura-ntco3,Consumo não-cíclico,Serviços e produtos pessoais e domésticos
2025-07-01 00:00:00-03:00,NATU3,36.860001,36.860001,36.860001,36.860001,0,ON,Natura,natura-ntco3,Consumo não-cíclico,Serviços e produtos pessoais e domésticos

In [15]:
# inserção de dados temporais no dataset
tbl_cotacao_ibovespa = dados_temporais(df=tbl_cotacao_ibovespa)
tbl_cotacao_ibovespa.head()

,ticker,Open,High,Low,Close,Volume,tipo,empresa,slug,setor,industria,dayofweek,month,Feriado
Date,,,,,,,,,,,,,,
2024-08-07 00:00:00-03:00,ABEV3,11.231811,11.687784,11.203895,11.641256,48591300,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,2,8,False
2024-08-08 00:00:00-03:00,ABEV3,11.594729,11.687785,11.455146,11.501673,28173200,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,3,8,False
2024-08-09 00:00:00-03:00,ABEV3,11.576117,11.613339,11.455145,11.585423,19122000,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,4,8,False
2024-08-12 00:00:00-03:00,ABEV3,11.631950,11.678478,11.529590,11.529590,17501300,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,0,8,False
2024-08-13 00:00:00-03:00,ABEV3,11.604034,11.780839,11.548200,11.697089,30082000,ON,Ambev S/A,ambev-abev3,Consumo não-cíclico,Bebidas,1,8,False

## Transformações

In [16]:
# transformação cíclica para dias uteis 
tbl_cotacao_ibovespa = transformacao_ciclica(df=tbl_cotacao_ibovespa, dias_uteis=True)

2025-10-14 19:23:38,611 | INFO | src.data.preprocessing | Transformação cíclica com dias úteis para as colunas de dados temporais.

In [17]:
# transformação da colunas Feriado no formato int
tbl_cotacao_ibovespa['Feriado'] = tbl_cotacao_ibovespa['Feriado'].astype(int)

In [18]:
# gerar diferenciação do target para revalidar a estacionariedade da serie
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Close')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Volume')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Open')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='High')
tbl_cotacao_ibovespa = diferenciar_serie_temporal(df=tbl_cotacao_ibovespa, target='Low')

In [19]:
# inserção das colunas de janela para o target e colunas de performance da ação
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Close_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Volume_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Open_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='High_diff')
tbl_cotacao_ibovespa = gerar_features_temporais(df=tbl_cotacao_ibovespa,coluna_valor='Low_diff')

In [20]:
tbl_cotacao_ibovespa['rsi'] = calcular_rsi(tbl_cotacao_ibovespa)

In [21]:
tbl_cotacao_ibovespa['macd'], tbl_cotacao_ibovespa['macd_signal'] = calcular_macd(tbl_cotacao_ibovespa)

In [22]:
# 1. Calcule o 'retorno' diário
tbl_cotacao_ibovespa['retorno_diario'] = tbl_cotacao_ibovespa.groupby('ticker')['Close'].pct_change()

# 2. Calcule a 'diferença do retorno'
# df['retorno_diff'] = retorno_hoje - retorno_ontem
tbl_cotacao_ibovespa['retorno_diff'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diario'].diff()

# 3. Aplique o 'lag' para evitar vazamento
# A nova feature "retorno_diff_lag1" representa a diferença do retorno do dia anterior vs. anteontem
tbl_cotacao_ibovespa['retorno_diff_lag1'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diff'].shift(1)

# 4. Remova as colunas intermediárias e os NaNs
tbl_cotacao_ibovespa = tbl_cotacao_ibovespa.drop(columns=['retorno_diario', 'retorno_diff'])

In [23]:
# 1. Calcule o 'retorno' diário
tbl_cotacao_ibovespa['retorno_diario_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['Volume'].pct_change()

# 2. Calcule a 'diferença do retorno'
# df['retorno_diff'] = retorno_hoje - retorno_ontem
tbl_cotacao_ibovespa['retorno_diff_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diario_volume'].diff()

# 3. Aplique o 'lag' para evitar vazamento
# A nova feature "retorno_diff_lag1" representa a diferença do retorno do dia anterior vs. anteontem
tbl_cotacao_ibovespa['retorno_diff_lag1_volume'] = tbl_cotacao_ibovespa.groupby('ticker')['retorno_diff_volume'].shift(1)

# 4. Remova as colunas intermediárias e os NaNs
tbl_cotacao_ibovespa = tbl_cotacao_ibovespa.drop(columns=['retorno_diario_volume', 'retorno_diff_volume'])

In [24]:
# remoção de linhas nulas para análise descritiva temporal
tbl_cotacao_ibovespa.dropna(inplace=True)

In [27]:
# análise da serie temporal
grafico_lineplot(df=tbl_cotacao_ibovespa, x_col=tbl_cotacao_ibovespa.index, 
                 y_col='Close', interativo=True, cat_col='ticker',
                 titulo='Gráfico de série temporal pela feature')

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

In [120]:
# análise boxplot interativa dos com escalonemanto dados 
grafico_boxplot(tbl_cotacao_ibovespa[['Open','High'	,'Low','Close', 'Volume','ticker']], cat_col='ticker', scaler=True, interativo=True)

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

In [ ]:
# histograma do target com escala
grafico_histograma(df=tbl_cotacao_ibovespa[['Open','High','Low','Close', 'Volume','ticker']], 
                   cat_col='ticker', interativo=True, scaler=True, 
           titulo='Histograma da coluna ticker')

interactive(children=(Dropdown(description='filtro', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

## Análise de estacionariedade da serie para definição de lags e médias móveis

In [ ]:
# teste de estacionariedade
teste_estacionariedade_interativo(df= tbl_cotacao_ibovespa, coluna_valor = 'Close')

interactive(children=(Dropdown(description='ticker', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

HTML(value='\n        <p>🔍 <strong>Teste ADF - Close | Ticker: ABEV3</strong></p>\n        <ul>\n            <…

In [121]:
# teste de estacionariedade
teste_estacionariedade_interativo(df= tbl_cotacao_ibovespa, coluna_valor = 'Close_diff')

interactive(children=(Dropdown(description='ticker', options=('ABEV3', 'ALOS3', 'ASAI3', 'AURE3', 'AZZA3', 'B3…

HTML(value='\n        <p>🔍 <strong>Teste ADF - Close_diff | Ticker: ABEV3</strong></p>\n        <ul>\n        …

In [109]:
# decomposicao da serie temporal diferenciada
grafico_decomposicao_temporal_interativo(df= tbl_cotacao_ibovespa, target = 'Close_diff', period=5)

VBox(children=(Dropdown(description='Ticker:', layout=Layout(width='300px'), options=('ABEV3', 'ALOS3', 'ASAI3…

In [110]:
# gráfico de autocorrelacao para definição do número de lags e médias móveis
grafico_acf_interativo(df=tbl_cotacao_ibovespa,coluna_valor = 'Close_diff',max_lags=30)

VBox(children=(Dropdown(description='Ticker:', layout=Layout(width='300px'), options=('ABEV3', 'ALOS3', 'ASAI3…

In [111]:
# gráfico de autocorrelacao parcial para definição do número de lags e médias móveis
grafico_pacf_interativo(df=tbl_cotacao_ibovespa,coluna_valor = 'Close_diff',max_lags=9)

KeyError: 'acao'

In [ ]:
# remoção de colunas para gerar dataset para validação de modelos
tbl_cotacao_ibovespa.drop(columns=['empresa','slug', 'Open', 'High','Low','Close','Volume','Feriado', 'month','dayofweek'], axis=1, inplace=True)

In [ ]:
# renome das colunas para treinamento do modelo
dicionario = {"ticker":"acao",
       "Close_diff":"close_diff", "lag_1_Close_diff":"lag_1_close_diff",
       "lag_2_Close_diff":"lag_2_close_diff", "lag_3_Close_diff":"lag_3_close_diff",
        "lag_5_Close_diff":"lag_5_close_diff",
       "rolling_mean_3_Close_diff":"rolling_mean_3_close_diff",
       "volatility_3_Close_diff":"volatility_3_close_diff",
       "retorno_acumulado_3_Close_diff":"retorno_acumulado_3_close_diff",
       "rolling_mean_5_Close_diff":"rolling_mean_5_close_diff",
       "volatility_5_Close_diff":"volatility_5_close_diff", 
       "retorno_acumulado_5_Close_diff":"retorno_acumulado_5_close_diff"}
tbl_cotacao_ibovespa.rename(columns=dicionario, inplace=True)

In [ ]:
# salvar o dataset para treino e validação dos modelos
tbl_cotacao_ibovespa.to_csv('../data/processed/tbl_cotacao_ibovespa_processed.csv', index=True)

# Insights do Análise Exploratória

# Recomendações de Transformações para o Pipeline

### Variáveis Numéricas

- **Normalização**: Foi observada alta variabilidade (maior que 3 desvios-padrão) em algumas colunas, com presença de valores zerados. Recomenda-se aplicar o `PowerTransformer` com o método *yeo-johnson* para ajustar a distribuição dessas variáveis.

- **Escalonamento**: Algumas colunas apresentam escalas muito distintas (ex: valores monetários vs. proporções decimais). Será aplicado `StandardScaler` para uniformizar a amplitude das variáveis e facilitar o aprendizado dos modelos.

- **Feature Engineering**:
  - Geração de colunas temporais a partir do índice `datetime`, incluindo marcações como dia da semana, fim de semana, feriado e dia útil.
  - Aplicação de codificação cíclica para atributos temporais (ex: dia do mês, dia da semana) a fim de preservar sua natureza periódica.
  - Diferenciação da variável target (primeira ordem) para suavizar tendências e preparar o dado para modelagem temporal.
  - Criação de variáveis derivadas com janelas móveis (lags, médias móveis, desvio-padrão e acumulados) para capturar padrões de dependência temporal.
  - Todas essas transformações serão integradas a um processo de ETL no AWS Glue.

---

### Variáveis Categóricas

- **Codificação (Encoding)**: Será utilizado *One-Hot Encoding* para variáveis com baixo número de categorias, garantindo interpretabilidade e boa performance nos modelos.

- **Feature Engineering**:
  - Aplicação de *Target Encoding* simples para a variável `acao`, devido ao número elevado de categorias e distribuição balanceada entre elas. Essa abordagem permite capturar a relação estatística entre a variável categórica e o target sem aumentar excessivamente a dimensionalidade.